spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: nabimoon7864@gmail.com
    password: kxbzwfzjjjisbzhj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


# 

# moqjgxdbvwpuqzz